package com.getbenefit.Orders;
// default package
// Generated Jun 29, 2017 3:30:28 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.getbenefit.Customer.Customers;

/**
 * CustomerOrders generated by hbm2java
 */
@Entity
@Table(name = "customer_orders", schema = "public")
public class Orders implements java.io.Serializable {

	private long orderid;
	private String item;
	private Customers customers;
	private long price;

	public Orders() {
	}

	public Orders(long orderid, String emailid, String item, long price) {
		this.orderid = orderid;
		this.customers=new Customers(emailid, "");
		this.item = item;
		this.price = price;
	}

	@Id

	@Column(name = "orderid", unique = true, nullable = false)
	public long getOrderid() {
		return this.orderid;
	}

	public void setOrderid(long orderid) {
		this.orderid = orderid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emailid", nullable = false)
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@Column(name = "item", nullable = false)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

}
